### ISSUE TITLE
Need reference to old desktop ID to fix gnome-software and the ODRS

### ISSUE THREAD

**Issue by hughsie** [flathub/net.sourceforge.Fillets#4]
In Fedora, the application ID is `fillets.desktop` but on flatpak it is `net.sourceforge.Fillets`. To "merge" the old and new IDs together in front-ends like gnome-software and KDE discover, and to use reviews reported against the old ID with the new ID you need to add an line in the existing `provides` section in the metainfo.xml file:

    <provides>
      <id>fillets.desktop</id>
    </provides>

See https://blogs.gnome.org/hughsie/2017/07/05/using-a-reverse-style-application-ids-in-your-application/ for more details.

**Comment by AsciiWolf** [comment]
Thanks, it should be fixed now. I will add this to my other Flatpaks as well when I have some free time.

**Comment by hughsie** [comment]
> I will add this to my other Flatpaks as well

Great, thanks. Ever one you fix makes the designers happy :)
